[build]
  command = "npm ci && npm run build"
  publish = "dist/meditation-ai-land-page"

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
